stages:
  - html_test
  - deploy_staging
  - deploy_production
  - clear


html_test:
  stage: html_test
  image: cyb3rjak3/html5validator:pypi
  script:
    - date=`date +"%d %B %Y (%T %Z)"`
    - sed -i "/BUILD_DATE/{s//$date/g}"  public/index.html
    - html5validator --root public/ --also-check-css --log INFO --ignore-re Attribute "built" Element "meta"
    - head public/index.html -n 20 | grep Built
  artifacts:
   paths:
     - public/*
   expire_in: 1 week

deploy_staging:
  image: cyb3rjak3/docker-curl-ssh
  before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_P_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - cat $SSH_KNOWN > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  stage: deploy_staging
  script:
  - scp -rp -P 2222 public/*  $DeployUser@$ServerIP:$RPath
  environment:
    name: Self_Host
    url: https://portfolio.jwhite.network
  only:
   - master

deploy_prod:
  image: devillex/docker-firebase
  stage: deploy_production
  script:
    - npm i -g firebase-tools
    - firebase use --token $FIREBASE_TOKEN personal-website-e2713
    - firebase deploy -m "Commit $CI_COMMIT_TITLE, Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
  environment:
    name: Public
    url: https://www.jwhite.network
  only:
    - master
  when: manual


  Clear_Cache:
  image: cyb3rjak3/docker-curl-ssh
  stage: clear
  needs:
  - deploy_production
  script:
  - chmod +x $script
  - bash $script