stages:
  - deploy1
  - deploy2


deploy_staging:
  image: kroniak/ssh-client
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_P_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - SSHKEY=`ssh-keyscan $ServerIP 2> /dev/null`
  - echo $SSHKEY > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  stage: deploy1
  script:
  - scp -rp -P 2222 /builds/jwhite1st/Portfolio-Website/public/*  $DeployUser@$ServerIP:$RPath
  environment:
    name: Self_Host
    url: https://portfolio.jwhite.network
  only:
   - master

deploy_prod:
  image: node:latest 
  stage: deploy2
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_TOKEN personal-website-e2713
    - firebase deploy -m "Commit $CI_COMMIT_TITLE, Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
  environment:
    name: Public
    url: https://www.jwhite.network
  only:
    - master
  when: manual