stages:
  - test

include:
  - template: SAST.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml

dast:
  stage: test
  variables: 
    DAST_WEBSITE: https://cyberjake.xyz
    DAST_FULL_SCAN_ENABLED: "true"
    DAST_REQUEST_HEADERS: "User-Agent: DAST/1.0"
  rules:
      - if: '$CI_COMMIT_BRANCH == "master" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
        changes:
        - public/*