stages:
  - html_test
  - deploy_staging
  - deploy_production


html_test:
  stage: html_test
  image: ubuntu:bionic
  before_script:
    - apt-get -qq update
    - apt-get install -y software-properties-common python-pip
    - add-apt-repository ppa:openjdk-r/ppa
    - apt-get -qq install -y openjdk-8-jre
    - pip install html5validator
  script:
    - html5validator --root public/


deploy_staging:
  image: kroniak/ssh-client
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_P_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - SSHKEY=`ssh-keyscan -p 2222 $ServerIP 2> /dev/null`
  - echo $SSHKEY > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  stage: deploy_staging
  script:
  - scp -rp -P 2222 /builds/jwhite1st/Portfolio-Website/public/*  $DeployUser@$ServerIP:$RPath
  environment:
    name: Self_Host
    url: https://portfolio.jwhite.network
  only:
   - master

deploy_prod:
  image: node:latest 
  stage: deploy_production
  cache:
    paths:
      - /usr/local/lib/node_modules/
  script:
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_TOKEN personal-website-e2713
    - firebase deploy -m "Commit $CI_COMMIT_TITLE, Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
  environment:
    name: Public
    url: https://www.jwhite.network
  only:
    - master
  when: manual