name: Build & Check

on:
  push:
    paths:
      - public/**
      - nginx.conf
      - Dockerfile
      - .github/workflows/main.yml

jobs:
  Docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_SLUG: ghcr.io/cyb3r-jak3/portfolio_website
    steps:
      - uses: actions/checkout@v3

      # - name: Change Date
        # run: |
        #     date=`date +"%d %B %Y (%T %Z)"`
        #     sed -i "/BUILD_DATE/{s//$date/g}"  public/index.html

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: HTML5 Validation
        uses: Cyb3r-Jak3/html5validator-action@v7.1.1
        with:
            root: public/
            format: json
            css: true
            log_level: INFO
            # extra: --ignore-re Attribute "built"

      - name: Login To GitHub
        uses: docker/login-action@v2 
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=true
          images: ${{ env.DOCKER_SLUG }}
          labels: |
            maintainer=Cyb3r Jak3 git@cyberjake.xyz
            org.opencontainers.image.vendor=cyb3rjak3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Portfolio Docker
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

