name: Build & Check

on:
  push:
    paths:
      - public/**
      - nginx.conf
      - Dockerfile
      - .github/workflows/main.yml

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

    - name: Login To GitHub
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

      - name: Build Portfolio Docker
        run: |
            date=`date +"%d %B %Y (%T %Z)"`
            sed -i "/BUILD_DATE/{s//$date/g}"  public/index.html
            head public/index.html -n 11 | grep Built
            docker build . --tag ghcr.io/cyb3r-jak3/portfolio_website:latest --cache-from ghcr.io/cyb3r-jak3/portfolio_website:latest

      - name: Inspect
        run: docker inspect ghcr.io/cyb3r-jak3/portfolio_website:latest 

      - name: Push
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: docker push ghcr.io/cyb3r-jak3/portfolio_website:latest