name: Build & Check

on:
  push:
    paths:
      - public/**
      - nginx.conf
      - Dockerfile
      - .github/workflows/main.yml

jobs:
  Docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_SLUG: ghcr.io/cyb3r-jak3/portfolio_website
    steps:
      - uses: actions/checkout@v2

      - name: Login To GitHub
        uses: docker/login-action@v1 
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=true
          images: ${{ env.DOCKER_SLUG }}
          labels: |
            maintainer=Cyb3r Jak3 jake@jwhite.network
            org.opencontainers.image.vendor=cyb3rjak3

      - name: Change Date
        run: |
            date=`date +"%d %B %Y (%T %Z)"`
            sed -i "/BUILD_DATE/{s//$date/g}"  public/index.html

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Build Portfolio Docker
        uses: docker/build-push-action@v2.7.0
        with:
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: ${{ github.event_name == 'push' && github.ref != 'refs/heads/master' }}
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Inspect
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: docker buildx imagetools inspect ${{ env.DOCKER_SLUG }}:latest

      - name: Inspect
        if: github.ref != 'refs/heads/master'
        run: docker inspect ${{ env.DOCKER_SLUG }}:latest
